#!/usr/bin/env node
const fs = require('fs');
function out(ok, data, error) { process.stdout.write(JSON.stringify(ok ? { code: 0, ok: true, data } : { code: 1, ok: false, error }) + '\n'); }
const args = process.argv.slice(2); const cmd = args[0] || '';
function dtUTC(d) { return d.toISOString().replace(/[-:]/g, '').replace(/\.\d{3}/, ''); }
function parseDT(s) { return new Date(s.replace(/(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})Z?/, '$1-$2-$3T$4:$5:$6Z')); }
try {
  if (cmd === 'status' || cmd === 'auth') return out(true, { ok: 'ics-builder ready' });
  if (cmd === 'create') { // create <标题> <开始YYYY-MM-DD[ HH:mm]> [结束或时长] [--file out.ics] [--desc 描述]
    const title = args[1]; if (!title) return out(false, null, '用法: ics-builder create <标题> <开始> [结束/时长] [--desc ...] [--file 路径]'); const pos = []; const kv = {}; for (let i = 2; i < args.length; i++) { const a = args[i]; if (a === '--file') { kv.file = args[i + 1]; i++; } else if (a === '--desc') { const seg = []; i++; while (i < args.length && !args[i].startsWith('--')) { seg.push(args[i]); i++; } kv.desc = seg.join(' '); i--; } else { pos.push(a); } }
    const startS0 = pos[0]; if (!startS0) return out(false, null, '缺少开始时间'); let startRaw = startS0; if (/^\d{4}-\d{2}-\d{2}$/.test(startS0) && pos[1] && /^\d{2}:\d{2}$/.test(pos[1])) { startRaw = startS0 + ' ' + pos[1]; pos.splice(1, 1); } const n1 = startRaw.replace(' ', 'T'); const start = new Date(/^\d{4}-\d{2}-\d{2}$/.test(n1) ? n1 + 'T00:00:00' : (n1.length === 16 ? n1 + ':00' : n1)); if (isNaN(start)) return out(false, null, '开始时间无效（用 YYYY-MM-DD 或 YYYY-MM-DD HH:mm）'); let end = null; if (pos[1]) { if (/^\d+(h|m|d)?$/.test(pos[1])) { const m = pos[1].match(/^(\d+)([hmd])?$/); const unit = m[2] || 'h'; const v = +m[1]; end = new Date(start.getTime() + v * (unit === 'h' ? 3600000 : unit === 'm' ? 60000 : 86400000)); } else { end = new Date(pos[1].replace(' ', 'T') + (/^\d{4}-\d{2}-\d{2}$/.test(pos[1]) ? 'T00:00:00' : '')); } }
    if (!end) end = new Date(start.getTime() + 3600000); const allDay = !startRaw.includes(':') && !(pos[1] && pos[1].includes(':'));
    const uid = Date.now() + '-' + Math.random().toString(36).slice(2, 10) + '@ics-builder';
    const ics = ['BEGIN:VCALENDAR', 'VERSION:2.0', 'PRODID:-//ics-builder//CN//EN', 'BEGIN:VEVENT', 'UID:' + uid, 'DTSTAMP:' + dtUTC(new Date()), allDay ? ('DTSTART;VALUE=DATE:' + start.toISOString().slice(0, 10).replace(/-/g, '')) : ('DTSTART:' + dtUTC(start)), allDay ? ('DTEND;VALUE=DATE:' + new Date(end.getTime() + 86400000).toISOString().slice(0, 10).replace(/-/g, '')) : ('DTEND:' + dtUTC(end)), 'SUMMARY:' + title.replace(/[\n,;]/g, ' '), ...(kv.desc ? ['DESCRIPTION:' + kv.desc.replace(/[\n,;]/g, ' ')] : []), 'END:VEVENT', 'END:VCALENDAR'].join('\r\n');
    if (kv.file) { fs.writeFileSync(kv.file, ics + '\r\n', 'utf-8'); return out(true, { saved: kv.file, summary: title, start: start.toString(), end: end.toString(), allDay }); }
    return out(true, { ics, summary: title, start: start.toString(), end: end.toString(), allDay, note: '可用 --file 保存为 .ics 文件导入日历' }); }
  if (cmd === 'parse') { const f = args[1]; if (!f) return out(false, null, '用法: ics-builder parse <文件.ics>'); const t = fs.readFileSync(f, 'utf-8'); const events = []; const cur = {}; const regs = /(DTSTART[^:]*):([^\r\n]+)/g; let m; const evts = t.split('BEGIN:VEVENT').slice(1); for (const e of evts) { const g = n => { const mm = e.match(new RegExp(n + '[^:]*:([^\\r\\n]+)')); return mm ? mm[1] : null; }; const summary = g('SUMMARY'); if (summary === null) continue; events.push({ summary: summary.replace(/\\,/g, ','), start: (g('DTSTART') || '').replace(/(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})/, '$1-$2-$3 $4:$5:$6').replace(/T(\d{2})(\d{2})(\d{2})/, ''), end: (g('DTEND') || g('DTSTART') || '').replace(/(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})/, '$1-$2-$3 $4:$5:$6') }); }
    return out(true, { file: f, count: events.length, events }); }
  if (cmd === 'free') { const fs2 = args.slice(1).filter(a => a.endsWith('.ics')); if (fs2.length < 2) return out(false, null, '用法: ics-builder free <文件1.ics> <文件2.ics> ... [--window 起 止]'); const busy = []; for (const f2 of fs2) { const t = fs.readFileSync(f2, 'utf-8'); for (const e of t.split('BEGIN:VEVENT').slice(1)) { const g = n => { const m2 = e.match(new RegExp(n + '[^:]*:([^\\r\\n]+)')); return m2 ? m2[1] : null; }; const s = g('DTSTART'), en = g('DTEND'); if (s) { busy.push([parseDT(s).getTime(), en ? parseDT(en).getTime() : parseDT(s).getTime() + 3600000]); } } }
    busy.sort((a, b) => a[0] - b[0]); const merged = []; for (const b of busy) { if (merged.length && b[0] <= merged[merged.length - 1][1]) merged[merged.length - 1][1] = Math.max(merged[merged.length - 1][1], b[1]); else merged.push([...b]); }
    const gaps = []; const now = Date.now(); let cursor = now; for (const [s, e] of merged) { if (s > cursor + 3600000) gaps.push({ from: new Date(cursor).toString(), to: new Date(s).toString() }); cursor = Math.max(cursor, e); }
    return out(true, { busyCount: busy.length, nextGap: gaps[0] || null, note: '基于提供的日历文件找空闲窗口（本地计算）' }); }
  return out(false, null, '未知命令。支持: status/auth/create/parse/free');
} catch (e) { out(false, null, '执行错误: ' + e.message); }
